Default: &defaults
  database: yesod-scaffold-email.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yesod-scaffold-email_test.sqlite3
  <<: *defaults

Staging:
  database: yesod-scaffold-email_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yesod-scaffold-email_production.sqlite3
  poolsize: 100
  <<: *defaults
